version: '3.8'

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - chromadb
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'CHROMA_HTTP_HOST=chromadb'
      - 'CHROMA_HTTP_PORT=8000'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  chromadb:
    volumes:
      - chromadb_data:/app/my_chroma_data
    image: chromadb/chroma:${CHROMA_DOCKER_TAG-latest}
    container_name: chromadb
    ports:
      - ${CHROMA_DB_PORT-8000}:8000
    environment:
      - CHROMA_DB_PATH=/app/my_chroma_data
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
  chromadb_data: {}
